quarkus:
#  kubernetes-config:
#    enabled: true
#    secrets:
#      ~: indy-repository-service-secrets
#      enabled: true
  http:
    port: 8080
    read-timeout: 30m
    limits:
      max-body-size: 500M

  package:
    uber-jar: true

  # Logging (disable console on prod)
  log:
    level: INFO
    min-level: INFO
    category:
      "org.jboss":
        level: WARN
      "io.quarkus":
        level: WARN
      "io.smallrye":
        level: WARN
      "org.eclipse":
        level: WARN
      "io.netty":
        level: WARN
      "org.infinispan":
        level: WARN
      "org.commonjava.indy.service":
        level: INFO
    console:
      enable: false
    file:
      level: INFO
      enable: true
      path: "log/indy-repository-service.log"
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      rotation:
        max-backup-index: 5
        max-file-size: 10M

  swagger-ui:
    always-include: true

repository:
  data-storage: cassandra
#  affectedGroupsExclude: ^build-\d+
#  disposableStorePattern:
  # ssl validation configuration for remote
#  remote:
#    sslRequired: false
#    nosslHosts: localhost,localhost1,localhost2


#keycloak:
#  enabled: false


cassandra:
  enabled: true
  host: localhost
  port: 9042
  user: testuser
  pass: testpass
  keyspace: indyreposervice
  keyspaceReplicas: 3
  replicaFactor: 3

#store:


"%dev":
   quarkus:
#     kubernetes-config:
#       enabled: false
     log:
       level: TRACE
       min-level: TRACE
       category:
         "org.jboss":
           level: INFO
         "io.quarkus":
           level: INFO
         "io.smallrye":
           level: INFO
         "org.eclipse":
           level: INFO
         "io.netty":
           level: INFO
         "org.infinispan":
           level: INFO
         "org.commonjava.indy.service":
           level: TRACE
       console:
         enable: true
       file:
         enable: true
         path: "/tmp/indy-repository-service.log"
         format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
         rotation:
           max-backup-index: 5
           max-file-size: 10M

   repository:
     data-storage: infinispan

   ispn:
     configDir: /tmp/infinispan.xml

   cassandra:
     enabled: false
     host: localhost
     port: 9042
     user: user
     pass: pass
#    keyspace:
#    replicaFactor:
#    keyspaceReplicas:
#    timeoutMillis:
#        connect: 60000
#        read: 60000
#    retries:
#        read: 3
#        write: 3






